services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DSN: "postgres://user:password@postgres:5432/music_library?sslmode=disable"
      MIGRATIONS_PATH: "file://migrations"
    command: ["./wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "./app"]

  postgres:
    restart: always
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_library
#    volumes:
#      - ./internal/pg/data:/var/lib/postgresql/data
