services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      DSN: "postgres://user:password@postgres:5432/music_library?sslmode=disable"
      MIGRATIONS_PATH: "file://migrations"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: "songs.updates"
      KAFKA_GROUP_ID: "songs_consumer_group"
      KAFKA_SESSION_TIMEOUT: "10"
#      MUSIC_INFO_API_URL: "http://music-info:8081"
    command: ["./wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "./app"]
    depends_on:
      - postgres
      - kafka
#      - music-info

  postgres:
    restart: always
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_library
#    volumes:
#      - ./internal/pg/data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  music-info:
#    build:
#      context: ./music-info
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
